### ISSUE TITLE
First state not releveant

### ISSUE THREAD

**Issue by YouriT** [VictorQueiroz/ui-router-history#2]
Hi,

Nice work on this, thank you! Just wanted to discuss something. I saw you register the first state which looks like this in my case
```json
{"name":"","url":"^","views":null,"abstract":true}
```

Therefore when you call ```$stateHistory.back()``` it thows an error because of the destination state.

So, what I would suggest is to ignore abstract states, if is that okay for you, then I will make a little pull request.

Cheers,

Youri

**Comment by VictorQueiroz** [comment]
Be my guest. Totally agree with you, can't see any reason to not ignore these states, so, I'm just waiting for your contribution. Thank you.

**Comment by YouriT** [comment]
great, but why do you store the start state which is an abstract with no state name ?

**Comment by VictorQueiroz** [comment]
I just didn't thought about it before. Anyway, thank you :+1:

**Comment by YouriT** [comment]
Good thanks :) could you push it to npm please?

**Comment by YouriT** [comment]
*bower

**Comment by VictorQueiroz** [comment]
Done! :)
